# 📖9.2 예외 처리 try-catch

finally에서 오류가 발생하면 어떻게 되나?

굳이 finally를 사용하지 않고 다음 줄에 이어서 작성하면 되지 않나?

